name: AWS Lambda Deploy using OIDC

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::924210590962:role/OIDC
          aws-region: us-east-1
          audience: sts.amazonaws.com
          output-env-credentials: true

      - name: Zip Lambda function
        run: zip function.zip lambda_function.py

      - name: Update Lambda code
        run: |
          aws lambda update-function-code \
            --function-name my-lambda-function \
            --zip-file fileb://function.zip

      - name: Verify Lambda update
        run: aws lambda get-function --function-name Test_for_OIDC
