name: AWS Lambda Deploy using OIDC

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::924210590962:role/OIDC
          aws-region: us-east-1
          audience: sts.amazonaws.com
          output-env-credentials: true

      # --- Loop for multiple Lambda functions ---
      - name: Deploy all Lambda functions
        run: |
          # SP
          zip -j Single_Asin_Multi_Product.zip src/SP/Single_Asin_Multi_Product/lambda_function.py
          aws lambda update-function-code --function-name Single_Asin_Multi_Product --zip-file fileb://Single_Asin_Multi_Product.zip

          zip -j Single_Assign_Single_Keywords.zip src/SP/Single_Assign_Single_Keywords/lambda_function.py
          aws lambda update-function-code --function-name Single_Assign_Single_Keywords --zip-file fileb://Single_Assign_Single_Keywords.zip

          zip -j Single_Asin_Single_Product.zip src/SP/Single_Asin_Single_Product/lambda_function.py
          aws lambda update-function-code --function-name Single_Asin_Single_Product --zip-file fileb://Single_Asin_Single_Product.zip

          zip -j Multi_asin_Multi_Keywords.zip src/SP/Multi_asin_Multi_Keywords/lambda_function.py
          aws lambda update-function-code --function-name Multi_asin_Multi_Keywords --zip-file fileb://Multi_asin_Multi_Keywords.zip

          zip -j Multi_Asin_Multi_Product.zip src/SP/Multi_Asin_Multi_Product/lambda_function.py
          aws lambda update-function-code --function-name Multi_Asin_Multi_Product --zip-file fileb://Multi_Asin_Multi_Product.zip

          zip -j Single_Assign_Multi_Keyword.zip src/SP/Single_Assign_Multi_Keyword/lambda_function.py
          aws lambda update-function-code --function-name Single_Assign_Multi_Keyword --zip-file fileb://Single_Assign_Multi_Keyword.zip

          # SD

          zip -j SD-Retarget.zip src/SP/SD-Retarget/lambda_function.py
          aws lambda update-function-code --function-name SD-Retarget --zip-file fileb://SD-Retarget.zip

          zip -j SD-Audience.zip src/SP/SD-Audience/lambda_function.py
          aws lambda update-function-code --function-name SD-Audience --zip-file fileb://SD-Audience.zip

          zip -j SD-Contextual-Prod.zip src/SP/SD-Contextual-Prod/lambda_function.py
          aws lambda update-function-code --function-name SD-Contextual-Prod --zip-file fileb://SD-Contextual-Prod.zip

          zip -j SD-Contextual-Category.zip src/SP/SD-Contextual-Category/lambda_function.py
          aws lambda update-function-code --function-name SD-Contextual-Category --zip-file fileb://SD-Contextual-Category.zip


      - name: Verify Lambda updates
        run: |
        # SP
          aws lambda get-function --function-name SD-Audience
          aws lambda get-function --function-name SD-Contextual-Category
          aws lambda get-function --function-name Single_Asin_Multi_Product
          aws lambda get-function --function-name Single_Assign_Single_Keywords
          aws lambda get-function --function-name Single_Asin_Single_Product
          aws lambda get-function --function-name Multi_asin_Multi_Keywords
          aws lambda get-function --function-name Multi_Asin_Multi_Product
          aws lambda get-function --function-name Single_Assign_Multi_Keyword

        # SD
          aws lambda get-function --function-name SD-Retarget
          aws lambda get-function --function-name SD-Audience
          aws lambda get-function --function-name SD-Contextual-Prod
          aws lambda get-function --function-name SD-Contextual-Category

        
